"""City-independent Urbanium core contracts."""

from urbanium.core.city import (
    CapabilityDefinition,
    CapabilitySupport,
    CityDefinition,
    LicenseMetadata,
    RedistributionStatus,
    SourceAuthority,
    SourceDefinition,
    SourceStatus,
    VersionIdentifier,
)
from urbanium.core.component import (
    CapabilityRequirement,
    ComponentDescriptor,
    ComponentKind,
    ComponentOutput,
    ComponentRegistry,
    ComponentResolution,
    DerivedStateCategory,
    ResolutionReasonCode,
    UnavailableCapability,
    resolve_component,
)
from urbanium.core.execution import (
    CapabilityInput,
    CapabilityInputProvenance,
    ComponentExecutionAttempt,
    ComponentExecutionOutcome,
    ComponentRunProblem,
    ComponentRunProvenance,
    ComponentRunResult,
    DerivedOutput,
    DeterministicComponent,
    RunStatus,
    execute_component,
    validate_component_run,
)

__all__ = [
    "CapabilityDefinition",
    "CapabilityInput",
    "CapabilityInputProvenance",
    "CapabilityRequirement",
    "CapabilitySupport",
    "CityDefinition",
    "ComponentDescriptor",
    "ComponentExecutionAttempt",
    "ComponentExecutionOutcome",
    "ComponentKind",
    "ComponentOutput",
    "ComponentRegistry",
    "ComponentResolution",
    "ComponentRunProblem",
    "ComponentRunProvenance",
    "ComponentRunResult",
    "DerivedOutput",
    "DerivedStateCategory",
    "DeterministicComponent",
    "LicenseMetadata",
    "RedistributionStatus",
    "ResolutionReasonCode",
    "RunStatus",
    "SourceAuthority",
    "SourceDefinition",
    "SourceStatus",
    "UnavailableCapability",
    "VersionIdentifier",
    "execute_component",
    "resolve_component",
    "validate_component_run",
]
